In [161]:
from IPython import get_ipython

if get_ipython():
    get_ipython().run_line_magic("load_ext", "autoreload")
    get_ipython().run_line_magic("autoreload", "2")

import numpy as np
import pandas as pd
import torch

import xarray as xr

import matplotlib.pyplot as plt
import seaborn as sns

import collections

import latenta as la

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [162]:
cells = la.Dim(pd.Series(range(100), name="cell").astype(str))
genes = la.Dim(pd.Series(range(4), name="gene").astype(str))
knots = la.Dim(range(11), "knot")

In [163]:
steps = torch.cat([torch.ones(len(knots)-1)])

steps = -torch.cat([torch.ones(len(knots)-1)])

steps = torch.cat([torch.ones(len(knots)-1)])
steps[:int(len(steps)/2)] *= -1

In [164]:
steps

tensor([-1., -1., -1., -1., -1.,  1.,  1.,  1.,  1.,  1.])

In [165]:
sign = torch.sigmoid(steps.sum())

In [166]:
sign

tensor(0.5000)

In [167]:
temperature = 0.1

In [168]:
step = la.distributions.HalfNormal()
step.run()

In [188]:
step_likelihood = step.log_prob(torch.exp(steps.abs()))

In [189]:
step_likelihood

tensor([-3.9203, -3.9203, -3.9203, -3.9203, -3.9203, -3.9203, -3.9203, -3.9203,
        -3.9203, -3.9203])

In [171]:
penalty_shift = 0.5
penalty_scale = 0.2
penalty_annealing = 1 # n_cells?

In [172]:
step_likelihood - penalty

tensor([-4.9203, -4.9203, -4.9203, -4.9203, -4.9203, -4.9203, -4.9203, -4.9203,
        -4.9203, -4.9203])

In [181]:
penalty_increasing = penalty_annealing * torch.sigmoid((-steps - penalty_cutoff)/penalty_scale) * sign
penalty_decreasing = penalty_annealing * torch.sigmoid((steps - penalty_cutoff)/penalty_scale) * (1-sign)

In [182]:
(-penalty_cutoff - steps)

tensor([ 0.5000,  0.5000,  0.5000,  0.5000,  0.5000, -1.5000, -1.5000, -1.5000,
        -1.5000, -1.5000])

In [183]:
(penalty_cutoff + steps)

tensor([-0.5000, -0.5000, -0.5000, -0.5000, -0.5000,  1.5000,  1.5000,  1.5000,
         1.5000,  1.5000])

In [186]:
penalty = penalty_increasing + penalty_decreasing

In [187]:
penalty

tensor([0.4623, 0.4623, 0.4623, 0.4623, 0.4623, 0.4623, 0.4623, 0.4623, 0.4623,
        0.4623])

In [95]:
sign

tensor(0.9933)